### ISSUE TITLE
bug restart the tunnel

### ISSUE THREAD

**Issue by Yogxx** [animegasan/luci-app-droidnet#1]
saat droidnetnya diaktifkan terus restart the tunnel tidak diaktifkan/centang, ketika tunnelnya bengong/dc harusnya cuma mode pesawat tapi tunnelnya ikut restart, itu termasuk bug kah atau emang fitur nya seperti itu?

**Comment by animegasan** [comment]
Seharusnya tidak, karena tidak tercentang

**Comment by animegasan** [comment]
Bisa dilihatkan log nya?

**Comment by Yogxx** [comment]
log nya aman ga ada notif error

**Comment by animegasan** [comment]
Iya, coba kirim saja, saya ingin lihat log yang dihasilkannya gimana

**Comment by Yogxx** [comment]
![Screenshot_2024-05-31-21-38-58-215_com sec android app sbrowser](https://github.com/animegasan/luci-app-droidnet/assets/163709469/7ee147c2-5a78-4223-8fa0-65a635d3011c)

**Comment by Yogxx** [comment]
sengaja saya ubah pingnya ke https biar failed, soalnya icmp succes, jarang bengong

posisi restart the tunnel ngga dicentang

**Comment by animegasan** [comment]
Iya benar, seharusnya tidak merestart tunneling tools karena di lognya pun sudah diberitahu kalau di skip

**Comment by animegasan** [comment]
https://github.com/animegasan/luci-app-droidnet/blob/6394e49373beba599a51e1bb92d179ecac11d12d/root/usr/share/droidnet/monitoring#L160

Kalau yang ini dihapus bagaimana ? Apakah masih merestart ?

**Comment by Yogxx** [comment]
aman bang, setelah hapus restart_interface tunnelnya ngga restart 
mantappp

**Comment by Yogxx** [comment]
saran aja kalo pingnya succes jamnya ikut berubah😁

**Comment by animegasan** [comment]
> aman bang, setelah hapus restart_interface tunnelnya ngga restart mantappp

Ok, berarti nanti saya coba untuk membuat menu agar restart_interfacenya di aktifkan atau tidak

> saran aja kalo pingnya succes jamnya ikut berubah😁

Maksudnya gimana??

**Comment by Yogxx** [comment]
![Screenshot_2024-05-31-22-12-44-600_com sec android app sbrowser](https://github.com/animegasan/luci-app-droidnet/assets/163709469/ac0a4fdb-c79d-441f-850b-1774c4681d8d)

**Comment by Yogxx** [comment]
jam di lognya ga mengikuti real time, dipojok kiri atas jam 22:12 tapi di lognya 10:05

**Comment by animegasan** [comment]
https://github.com/animegasan/luci-app-droidnet/blob/6394e49373beba599a51e1bb92d179ecac11d12d/root/usr/share/droidnet/monitoring#L27

Itu Mengikuti local. Jadi jika jam tidak sesuai maka bermasalah di jam STB nya

**Comment by Yogxx** [comment]
oh, oke sip makasih atas jawabannya 😁

**Comment by anasfanani** [comment]
> https://github.com/animegasan/luci-app-droidnet/blob/6394e49373beba599a51e1bb92d179ecac11d12d/root/usr/share/droidnet/monitoring#L27
> 
> Itu Mengikuti local. Jadi jika jam tidak sesuai maka bermasalah di jam STB nya

Mungkin maksudnya kurang detik bg.

```
echo "$(date +"%a, %b %d, %I:%M:%S %p") - Monitoring service: $1" >> /var/log/droidnet.log
```
