### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by ntbowen** [animegasan/luci-app-droidnet#3]
os: Ubuntu 22.04.4 LTS
luci: R23.05
kernel:6.6.36
souce code: [lean](https://github.com/coolsnowwolf/lede)
issue:
erro log:
make[3]: Entering directory '/home/ntbowen/openwrt/lean/package/base-files'
mkdir -p /home/ntbowen/openwrt/lean/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /home/ntbowen/openwrt/lean/tmp/.root-copy.flock -c 'cp -fpR /home/ntbowen/openwrt/lean/build_dir/target-x86_64_musl/linux-x86_64/base-files/.pkgdir/base-files/. /home/ntbowen/openwrt/lean/staging_dir/target-x86_64_musl/root-x86/'
cp: cannot overwrite directory '/home/ntbowen/openwrt/lean/staging_dir/target-x86_64_musl/root-x86/./var' with non-directory
make[3]: *** [Makefile:251: /home/ntbowen/openwrt/lean/staging_dir/target-x86_64_musl/root-x86/stamp/.base-files_installed] Error 1
make[3]: Leaving directory '/home/ntbowen/openwrt/lean/package/base-files'
time: package/base-files/compile#0.15#0.01#0.16
    ERROR: package/base-files failed to build.
make[2]: *** [package/Makefile:116: package/base-files/compile] Error 1
make[2]: Leaving directory '/home/ntbowen/openwrt/lean'
make[1]: *** [package/Makefile:110: /home/ntbowen/openwrt/lean/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ntbowen/openwrt/lean'
make: *** [/home/ntbowen/openwrt/lean/include/toplevel.mk:231：world] 错误 2

**Comment by animegasan** [comment]
Error cannot overwrite directory..
Please check your git clone lean

**Comment by animegasan** [comment]
If there is no progress I close first.

Thank
