### ISSUE TITLE
建议修改日志文件的路径

### ISSUE THREAD

**Issue by ntbowen** [animegasan/luci-app-droidnet#4]
建议修改/root/var/log/droidnet.log的路径，比如/root/etc/log/droidnet.log，否则会导致某些openwrt（例如lean的源码）编译base-filess时出错，具体错误如下：
make[3]: Entering directory '/home/ntbowen/openwrt/coolsnowwolf/package/base-files'
mkdir -p /home/ntbowen/openwrt/coolsnowwolf/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp
SHELL= flock /home/ntbowen/openwrt/coolsnowwolf/tmp/.root-copy.flock -c 'cp -fpR /home/ntbowen/openwrt/coolsnowwolf/build_dir/target-aarch64_generic_musl/linux-rockchip_armv8/base-files/.pkgdir/base-files/. /home/ntbowen/openwrt/coolsnowwolf/staging_dir/target-aarch64_generic_musl/root-rockchip/'
cp: cannot overwrite directory '/home/ntbowen/openwrt/coolsnowwolf/staging_dir/target-aarch64_generic_musl/root-rockchip/./var' with non-directory
make[3]: *** [Makefile:251: /home/ntbowen/openwrt/coolsnowwolf/staging_dir/target-aarch64_generic_musl/root-rockchip/stamp/.base-files_installed] Error 1
make[3]: Leaving directory '/home/ntbowen/openwrt/coolsnowwolf/package/base-files'
time: package/base-files/compile#0.12#0.09#0.21
    ERROR: package/base-files failed to build.
make[2]: *** [package/Makefile:116: package/base-files/compile] Error 1
make[2]: Leaving directory '/home/ntbowen/openwrt/coolsnowwolf'
make[1]: *** [package/Makefile:110: /home/ntbowen/openwrt/coolsnowwolf/staging_dir/target-aarch64_generic_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/ntbowen/openwrt/coolsnowwolf'
make: *** [/home/ntbowen/openwrt/coolsnowwolf/include/toplevel.mk:231：world] 错误 2

修改路径后即可解决问题

**Comment by animegasan** [comment]
![image](https://github.com/user-attachments/assets/e73da7d6-c4ac-4606-a2d2-742a2aef57e3)
How about putting the file in the tmp folder?
So that every time the device reboots the log file will always be new.

**Comment by ntbowen** [comment]
> ![image](https://private-user-images.githubusercontent.com/14136053/371873521-e73da7d6-c4ac-4606-a2d2-742a2aef57e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2NTg5MjQsIm5iZiI6MTcyNzY1ODYyNCwicGF0aCI6Ii8xNDEzNjA1My8zNzE4NzM1MjEtZTczZGE3ZDYtYzRhYy00NjA2LWEyZDItNzQyYTJhZWY1N2UzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDAxMTAyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNzAwZTVmMjI4ODA5YTJjZmU4NzE3N2E0ZWNjNzMyZGNjZTVhZGVmMGJhNDhhYmRmZGY0ZmIyNDE4MGYwOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IoDMzk8Z65VQnB4IjM_NBJiq1KgYjPISqMF4qy-UpW4) How about putting the file in the tmp folder? So that every time the device reboots the log file will always be new.

这样也可以，不过存放临时文件夹的方式会把旧的日志给覆盖掉，如果因为这个app导致系统死机重启，再回来看日志是无效的。有没有考虑过把日志增加时间戳累计存储。

**Comment by animegasan** [comment]
> 这样也可以，不过存放临时文件夹的方式会把旧的日志给覆盖掉，如果因为这个app导致系统死机重启，再回来看日志是无效的。有没有考虑过把日志增加时间戳累计存储。

I was just thinking about what you said and it does seem to make sense to save to /etc so we can look back at the last log before restarting. Using a stamp on the log file seems like a last resort to me since there is a lot of code involved in logging. So saving to the etc folder makes more sense. Thanks for the idea and explanation!
